[package]
name = "db-sight-core"
version = "0.1.0"
authors = ["MuzzyLip <muzzylip@gmail.com>"]
edition = "2021"

[dependencies]
uuid = "1.18.1"
# Local Crate
db-sight-assets = { workspace = true }
