[package]
name = "db-sight-assets"
version = "0.1.0"
authors = ["MuzzyLip <muzzylip@gmail.com>"]
edition = "2021"

[dependencies]
gpui = { workspace = true }
gpui-component = { workspace = true }
